SET TRUENULLCREATE = OFF;CREATE TABLE "GCG5_5818_QUAL_UF" (
 "CONTROL_NUMBER" CHAR(7),
 "USERFIELD_1" LONGVARCHAR,
 "USERFIELD_2" LONGVARCHAR,
 "USERFIELD_3" LONGVARCHAR,
 "USERFIELD_4" LONGVARCHAR,
 "USERFIELD_5" LONGVARCHAR );SET TRUENULLCREATE = ON;